packages:
  - "apps/*"
  - "packages/*"


allowBuilds:
  esbuild: false
  unrs-resolver: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.27'
  - '@expo/router-server@57.0.11'
  - babel-preset-expo@57.0.13
  - expo-modules-core@57.0.19
  - expo-modules-jsi@57.1.1
  - expo@57.0.25
  - '@expo/ui@57.0.20'
  - expo-glass-effect@57.0.4
  - expo-linking@57.0.11
  - expo-router@57.0.23
